### ISSUE TITLE
Question: how to use wake on lan via Docker image

### ISSUE THREAD

**Issue by bertoost** [joshuacox/mkdomoticz#14]
Just needs an answer on how to configure hardware/devices to use wake-on-lan from the Docker container. Thanks in advance.

Regards, Bert

**Comment by bertoost** [comment]
FYI; I can't use `network_mode: host` since another proxy tool is already using port 8080.

**Comment by joshuacox** [comment]
`make port`  will ask you for the port you want.

Or  `echo 5080 > PORT` or edit that file directly with your preferred text editor.  Which is read by the Makefile for the docker run commands.  Feel free to re-open if you have more questions.

Thanks for your feedback!  I will try and cut a new rpi image soon.

**Comment by bertoost** [comment]
I was able to change the 8080 port from the other tool. So I can setup `network_mode: host`. Therefor WOL not working yet. I have to check my bios settings of the pc I want to WOL

**Comment by joshuacox** [comment]
Interesting, I am not certain domoticz will work right on something that is going to sleep like that.

**Comment by bertoost** [comment]
I have turned on WOL on my PC's bios. Unfortunate not working yet. I saw at normal boot that the network connection was not established right away (a warning triangle was shown for a second). So that's probably something I have to figure out before.
Thanks anyway for the quick response here.
