### ISSUE TITLE
Domoticz is compiled with a fixed timezone

### ISSUE THREAD

**Issue by czettnersandor** [joshuacox/mkdomoticz#18]
Domoticz is showing incorrect time on the frontend despite the host's timezone is set to Europe/London

**Comment by joshuacox** [comment]
this is set by the [TZ variable](https://github.com/joshuacox/mkdomoticz/blob/master/Makefile#L84)

which can be permanently set with `make TZ` of which you can see the source [here](https://github.com/joshuacox/mkdomoticz/blob/master/Makefile#L124)  

feel free to re-open if it still doesn't work for you
