### ISSUE TITLE
Request: add support for wemo device

### ISSUE THREAD

**Issue by taspts** [joshuacox/mkdomoticz#2]
I need wemo bridge access

Dockerfile
RUN pip install -U ouimeaux

or clone  https://github.com/iancmcc/ouimeaux in build process
should run in python3
And provide wemo command to query a wemo bridge

**Comment by joshuacox** [comment]
I used pip3, it is building now:

https://hub.docker.com/r/joshuacox/mkdomoticz/builds/

feel free to reopen if I can do anything else to help.

EDIT: I also updated all the branches in case you were using the local-stretch.  I won't get around to building the arm image till I get back to Austin (next week), so best to build with local-stretch if on a rPi or similar.

**Comment by joshuacox** [comment]
back in Austin now and I uploaded a new image to the docker hub mkdomoticz arm tag: https://hub.docker.com/r/joshuacox/mkdomoticz/tags/

now `make pull` should work from the arm branch of this repo, and hence `make init` and subsequently `make run` will use the prebuilt image if you like (saves hours of compilation time)
