### ISSUE TITLE
update domoticz version

### ISSUE THREAD

**Issue by Stijn98s** [joshuacox/mkdomoticz#21]
Is it possible to rebuild the image so the newest stable version from domoticz is used? Currently it is v4.10364 and latest stable is v4.10717

**Comment by alan-rpi** [comment]
I would support this as well. I think I read the current Docker Domoticz is based on Stretch. I'm using Buster. Will the the current Docker Domoticz work on Buster or is a new version needed?

**Comment by uermend** [comment]
I'm interested in a new Domoticz image just like Stijn98s.

**Comment by joshuacox** [comment]
@uermend @alan-rpi @Stijn98s pushing a new image now, sorry for all the delay here but domoticz requires a newer cmake than is available in both stretch and buster, so I just threw in a script to compile it as well.  I might make a binary branch that does not compile domotticz from scratch and make it master/latest.  Give the new image a shot, and feel free to re-open or create a new issue.
