### ISSUE TITLE
404 Not found message after installation

### ISSUE THREAD

**Issue by roelbeun** [joshuacox/mkdomoticz#3]
Hi,

I did a pull and then the frist command to extract the config data to local dir, then i did:

`docker run -d --name domoticz --privileged --cidfile="/mnt/docker_data/cids/domoticz-cid" -p 8080:8080/tcp -v `pwd`/mnt/docker_data/domoticz/config:/config -t joshuacox/mkdomoticz`

The container runs but when i go to the sever_ip:8080 i'am getting a message 404 Not found. Only related topic regarding this is:

[Domoticz topic](https://www.domoticz.com/forum/viewtopic.php?t=9062)

Logs say:
`docker logs -f domoticz`

> 2017-06-28 05:52:59.383  Domoticz V3.7502 (c)2012-2017 GizMoCuz
> 2017-06-28 05:52:59.383  Build Hash: fdc764ee, Date: 2017-05-23 11:06:41
> 2017-06-28 05:52:59.384  Startup Path: /usr/local/bin/
> 2017-06-28 05:52:59.387  BuildManifest: Created directory /usr/local/bin/plugins/
> 2017-06-28 05:52:59.403  PluginSystem: Started, Python version '3.5.3'.
> 2017-06-28 05:52:59.404  Active notification Subsystems: gcm, http (2/12)
> 2017-06-28 05:52:59.404  WebServer(HTTP) started on address: 0.0.0.0 with port 8080
> 2017-06-28 05:52:59.405  Error: WebServer(SSL) startup failed on address 0.0.0.0 with port: 443: use_certificate_chain_file: No such file or directory
> 2017-06-28 05:52:59.405  Error: WebServer(SSL) check privileges for opening ports below 1024
> 2017-06-28 05:52:59.405  Proxymanager started.
> 2017-06-28 05:52:59.405  Starting shared server on: 0.0.0.0:6144
> 2017-06-28 05:52:59.405  RxQueue: queue worker started...
> 2017-06-28 05:52:59.405  TCPServer: shared server started...
> 2017-06-28 05:53:01.407  EventSystem: reset all events...
> 2017-06-28 05:53:01.407  EventSystem: reset all device statuses...
> 2017-06-28 05:53:01.407  EventSystem: Started
> 2017-06-28 05:53:01.891  PluginSystem: Entering work loop.
> 2017-06-28 05:53:03.427  Incoming connection from: 192.168.0.4

Any advice to solve this?

**Comment by joshuacox** [comment]
I am pretty sure I broke it a month ago trying to slim down the image, rebuiding [now](https://hub.docker.com/r/joshuacox/mkdomoticz/builds/)

**Comment by joshuacox** [comment]
ok the current 'latest' tag should work, I am cleaning up a few things, but it should be back to working, I am separating out the LOGDIR as it's own volume, and I put a `DOMOTICZ_OPTS` in there that can be used to test some of the other features.

**Comment by roelbeun** [comment]
works like a charm, thanks!

**Comment by joshuacox** [comment]
there's a `20170628` tag for todays release as well, to prevent future problems
