### ISSUE TITLE
Aligned images for stable builds + ARG domoticz_version on Dockerfiles

### ISSUE THREAD

**Issue by glecoz** [joshuacox/mkdomoticz#6]
Hi, first of all thanks for building and maintaining the only functional Docker images and Dockerfiles I could find for Domoticz containers on Raspberry Pi :)

I'm currently Dockerizing my existing Domoticz on the following context :

* High powered main server (amd64)
* Backup server (arm / Raspberry Pi 3 B+)

The backup server being used only when the main one is under maintenance. In such context,  Domoticz persisted data and config must be transferred back and forth between containers on both servers, with the same Domoticz versions, to avoid hazardous automated up/down migrations on Domoticz database between both instances relying on different CPU architectures.

So, could you provide images of the latest Domoticz stable version (3.8153 and further ones when available) on Docker Hub for both your strech and arm-stretch branches ? 

Like :

* stretch-stable-3.8153
* arm-stable-3.8153

I guess this would be useful to many users, since [your images](https://hub.docker.com/r/joshuacox/mkdomoticz/tags) for those branches are currently built on different periods, and relying on Domoticz master (beta) branch :

* stretch : 9 months ago
* arm : 11 days ago

Or, at least, could you provide an argument for the Domoticz version on your stretch and stretch-arm Dockerfiles, so that anyone can build the same Domoticz version on both architectures ? 

This way any user can override these settings upon build from command line or docker-compose files to build from any Domoticz tag or the master branch :

```
# Domoticz
  ha-domoticz:
    build:
      context: ./domoticz/build/arm  # (<- mkdomoticz Dockerfile)
      args:
        DOMOTICZ_VERSION: 3.8153      # (or master)
```

Please check my pull requests below. 

Thanks.

**Comment by joshuacox** [comment]
I am sorry this issue got stale, as you can see I merged your PRs, but if there is anything else you need would you please re-open this issue and explain more that I might be able to help with?

Thanks again for the PR!  Sorry I let this get stale.
